remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Site Settings
title: Kerb Writeups
author: Kerburenthusiasm
description: CTF Writeups and Security Research
baseurl: /kerbwriteups
url: "https://Kerburenthusiasm.github.io"

# Jekyll Settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Exclude from processing
exclude:
  - .github/
  - vendor